
###

GET http://localhost:3333/categories HTTP/1.1

####
POST http://localhost:3333/products HTTP/1.1
Content-Type: application/json

{
  "name": "X AMERICAsNO",
  "description": "Pao, ovo, presunto e queiro",
  "categoryGuid": "909b80b3-0ae3-4210-8faa-b7171f2315ea",
  "price": 19.99
}


####
POST http://localhost:3333/orders HTTP/1.1
Content-Type: application/json

{
   "userId": 1,
   "total": 0,
   "orderItem": [{
    "productId": 1,
    "quantity": 12
   }]
}

