
###

GET http://localhost:3333/products HTTP/1.1

####
POST http://localhost:3333/sizes HTTP/1.1
Content-Type: application/json

{
  "name": "Pequena",
  "price": 0
}


####
POST http://localhost:3333/orders HTTP/1.1
Content-Type: application/json

{
   "userId": 1,
   "total": 0,
   "orderItem": [{
    "productId": 1,
    "OrderItemSizeId": 3,
    "quantity": 12
   }]
}

