
###

GET http://localhost:3333/products HTTP/1.1

####
POST http://localhost:3333/products HTTP/1.1
Content-Type: application/json

{
  "name": "X AMERICAsNO",
  "description": "Pao, ovo, presunto e queiro",
  "categoryGuid": "e53e9063-f4f7-450d-82ec-00b5c93507f7",
  "price": 19.99,
  "dayOfWeek": "Segunda",
  "fileGuid": "f651458e-a150-4dc8-a052-211bd0f10ad5"
}


####
POST http://localhost:3333/orders HTTP/1.1
Content-Type: application/json

{
   "userId": 1,
   "total": 0,
   "orderItem": [{
    "productId": 1,
    "quantity": 12
   }]
}

